---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(monocle3)
library(Seurat)
library(patchwork)
library(mclust)
library(SeuratWrappers)
library(ggplot2)
```


```{r}
tabData=readRDS("../ScRNASeq-hackathon/Nestorowa.rds")
tabData[1:4, 1:4]
```


```{r}
tabmur <- CreateSeuratObject(
  counts = tabData,
  project = "tabulamuris",
  min.cells = round(dim(tabData)[2]*5/100),
  min.features = 0
)
```


```{r}
tabmur
tabmur@assays$RNA@counts[1:4,1:4]
summary(Matrix::colSums(tabData))
hist(Matrix::colSums(tabData), xlab="Total Counts", breaks=100,  ylab="Number of cells")  
```


```{r}
tabmur[["percent.mt"]] <- PercentageFeatureSet(tabmur, pattern = "^mt-")

plot1 <- VlnPlot(tabmur, features = c("nFeature_RNA"), ncol=1)
plot1
plot2 <- VlnPlot(tabmur, features = c("nCount_RNA"), ncol=1)
plot2

plot4 <- VlnPlot(tabmur, features = c("percent.mt"), ncol = 1) + 
  geom_abline(intercept=12, linetype=2, slope=0)
plot4

plot3 <- FeatureScatter(tabmur,
    feature1 = "nCount_RNA",
    feature2 = "nFeature_RNA",
    group.by = "orig.ident"
) +
  geom_vline(
    xintercept=0.7*1e7,
    linetype=2
  ) +
  geom_hline(
    yintercept=16000,
    linetype=2
  )

plot3
```

```{r}
tabmur <- subset(tabmur, subset = nFeature_RNA > 400 & nFeature_RNA < 16000 & nCount_RNA > 400 & nCount_RNA < 1e7 & percent.mt < 12)
tabmur
```


```{r}
tabmur <- NormalizeData(tabmur, normalization.method = "LogNormalize", scale.factor = 10000)

tabmur@assays$RNA@data[1:5,1:5]
```

```{r}
tabmur <- FindVariableFeatures(object = tabmur, selection.method="vst", nfeatures = 2000)
top10 <- head(VariableFeatures(tabmur), 10)
plot1 <- VariableFeaturePlot(tabmur)
plot1
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot2
```


```{r}
tabmur <- ScaleData(tabmur, do.center = TRUE, do.scale = TRUE)
tabmur@assays$RNA@scale.data[1:5,1:5]
```


```{r}
tabmur <- RunPCA(tabmur, features = VariableFeatures(object = tabmur))

plot1 <- DimPlot(tabmur, reduction = "pca")
plot1

plot2 <- VizDimLoadings(tabmur, dims = 1:2, reduction = "pca")
plot2

tabmur <- JackStraw(tabmur, num.replicate = 100)
tabmur <- ScoreJackStraw(tabmur, dims = 1:20)
JackStrawPlot(tabmur, dims = 1:15)
ElbowPlot(tabmur,ndims=100)
```

```{r}
cs <- cumsum(tabmur@reductions$pca@stdev)
cs / cs[50]
```


```{r}
tabmur <- FindNeighbors(tabmur, dims = 1:50)
tabmur <- FindClusters(tabmur, resolution = 0.5)
table(Idents(tabmur))
```

```{r}

tabmur <- RunUMAP(tabmur, dims = 1:50)
DimPlot(tabmur, group.by = "ident", reduction = "umap")
DimPlot(tabmur, group.by = "orig.ident", reduction = "umap")
```

```{r}
tabmur <- RunTSNE(tabmur, dims = 1:50)
DimPlot(tabmur, group.by = "ident", reduction = "tsne")
DimPlot(tabmur, group.by = "orig.ident", reduction = "tsne")
```

```{r}
adjustedRandIndex(Idents(tabmur), tabmur@meta.data$orig.ident)
```

```{r}
tabmur.markers <- FindAllMarkers(tabmur, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
```

```{r}
tabmur.markers %>%
    group_by(cluster) %>%
    slice_max(n = 2, order_by = avg_log2FC)
```

```{r}
summary(tabmur@assays$RNA@counts["Mfsd2b", ])
```

```{r}
cluster1.markers <- FindMarkers(tabmur, ident.1 = 1, min.pct = 0.25)
cluster1.markers[1, ]
cluster2.markers <- FindMarkers(tabmur, ident.1 = 2, min.pct = 0.25)
cluster2.markers[1, ]
cluster3.markers <- FindMarkers(tabmur, ident.1 = 3, min.pct = 0.25)
cluster3.markers[1, ]
cluster4.markers <- FindMarkers(tabmur, ident.1 = 4, min.pct = 0.25)
cluster4.markers[1, ]
cluster5.markers <- FindMarkers(tabmur, ident.1 = 5, min.pct = 0.25)
cluster5.markers[1, ]
```


```{r}
plot1<-VlnPlot(tabmur, features = c("Mfsd2b", "Epx", "Pklr", "Pdzk1ip1", "Pou2af1"),idents = c(0,3,5))
plot1

plot2<-FeaturePlot(tabmur, features = c("Mfsd2b", "Epx", "Pklr", "Pdzk1ip1", "Pou2af1"))
plot2

tabmur.markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = avg_log2FC) -> top10
```

```{r}
monocle_object <- as.cell_data_set(tabmur)
monocle_object <- cluster_cells(cds = monocle_object, reduction_method = "UMAP")

p1<- plot_cells(monocle_object, show_trajectory_graph = FALSE)
p2 <- plot_cells(monocle_object, color_cells_by = "partition", show_trajectory_graph = FALSE)
#wrap_plots(p1, p2)
p1
```
```{r}
#integrated.sub <- subset(as.Seurat(monocle_object), monocle3_partitions == 2)
#cds <- as.cell_data_set(integrated.sub)
```



```{r}
monocle_object <- learn_graph(monocle_object)
plot4<- plot_cells(monocle_object, label_groups_by_cluster = FALSE, label_leaves = FALSE, label_branch_points = FALSE)
plot4

get_correct_root_state <- function(cds,cell_phenotype = 'orig.ident', time_bin="LT-HSC"){
  cell_ids <- which(colData(cds)[, cell_phenotype] == time_bin)
  
  closest_vertex <-
  cds@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex
  closest_vertex <- as.matrix(closest_vertex[colnames(cds), ])
  root_pr_nodes <-
  igraph::V(principal_graph(cds)[["UMAP"]])$name[as.numeric(names
  (which.max(table(closest_vertex[cell_ids,]))))]
  
  root_pr_nodes
}


node_ids = get_correct_root_state(monocle_object) 

#where cell_phenotypes indicates the column where cell types are stored, while root_type is the cell_type we want to select.


monocle_object <- order_cells(monocle_object,root_pr_nodes = node_ids)
```

```{r}
plot_cells(monocle_object,
       color_cells_by = "pseudotime",
       graph_label_size=1,
       show_trajectory_graph = TRUE)
```